k, j, h = input().split()
k = int(k)
j = int(j)
h = int(h)
nk, nj, nh = input().split()
nk = int(nk)
nj = int(nj)
nh = int(nh)
print(int(k+nk).__str__() + " " + int(j+nj).__str__() + " " + int(h+nh).__str__())